# Site settings
title: Tamim Sookoor
email: tamimsookoor@gmail.com
url: https://sookoor.github.io
description: "Tamim Sookoor is a Senior Cyberphysical Researcher at G2, Inc. This site presents his research, projects, and publications."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Tamim Sookoor
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    #  - title: twitter
    #url: http://twitter.com/jekyllrb
    #  - title: facebook
    #    url:
  - title: linkedin
    url: https://www.linkedin.com/in/sookoor
  - title: stack-overflow
    url: https://careers.stackoverflow.com/sookoor
  - title: bitbucket
    url: http://bitbucket.org/sookoor
  - title: github
    url: http://github.com/sookoor
  - title: google-plus
    url: https://www.google.com/+TamimSookoor

# Postal address (add as many lines as necessary)
address:
  - line: 169 Chapeltowne Cir
  - line: Nottingham, MD 21236

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
